### ISSUE TITLE
R ignoring openmp on osx

### ISSUE THREAD

**Issue by beckermr** [conda-forge/xgboost-feedstock#41]
The R build is ignoring openmp on osx.

**Comment by jakirkham** [comment]
I wonder if something is going on [in here]( https://github.com/dmlc/xgboost/blob/515f5f5c4779ff5361dcd796e22d55937e1048ea/R-package/configure#L1673-L1696 ).

**Comment by jakirkham** [comment]
That said, does OpenMP actually get used in the R bindings? Or is it actually just used in `libxgboost`, which the bindings merely call? If it's the latter, then maybe the issue is that Linux is adding an extra linkage to R binding package that it shouldn't.

**Comment by beckermr** [comment]
IDK much about the internals. I did notice in the configure script for the R build it says it is not finding openmp. 

Also, I don't see where the R build actually links to libxgboost. I am not confident it is actuall using the code there. Conda build certainly is not finding any linkages.

**Comment by jakirkham** [comment]
Yeah there appears to be some [C binding code for the R package]( https://github.com/dmlc/xgboost/tree/v0.90/R-package/src ).

Now that I'm looking at it, it does appear to be using OpenMP.

**Comment by jakirkham** [comment]
@RAMitchell, would you be able to advise us on how to proceed here?

**Comment by RAMitchell** [comment]
I'm not familiar with osx or R. @hcho3/@trivialfis do you have any ideas?

**Comment by hcho3** [comment]
There are two ways to build XGBoost-R package. 

1. Using `install.packages()`. This will download a tarball from CRAN and build XGBoost using GNU toolchains. Since Apple Clang doesn't support OpenMP out of box, we disable OpenMP for this use scenario.

2. Using CMake. The user can check out the XGBoost code using git and use CMake to build XGBoost with R binding. In this case, OpenMP will be enabled.

**Comment by jakirkham** [comment]
Thanks for the feedback.

We are [using git to download the code]( https://github.com/conda-forge/xgboost-feedstock/blob/23eaf9a71f994dfac45bd69cd1b88a42a5238d86/recipe/meta.yaml#L11-L12 ), but it appears we are using [`r cmd install --build`]( https://github.com/conda-forge/xgboost-feedstock/blob/23eaf9a71f994dfac45bd69cd1b88a42a5238d86/recipe/install-r-xgboost.sh#L16 ) instead of CMake for the build of the R bindings. So it sounds like we should change that to CMake then.

Yeah there is pretty large set of R packages in conda-forge and a decent number of downstream users of them.

**Comment by hcho3** [comment]
@jakirkham Yes, I'd say that CMake is your best bet. I just wish that CRAN builds supported CMake too.

**Comment by jakirkham** [comment]
Thanks for the advice. Giving this a try in PR ( https://github.com/conda-forge/xgboost-feedstock/pull/42 ).

**Comment by jakirkham** [comment]
We've since moved to CMake. Please let us know if you are still encountering issues though

**Comment by jakirkham** [comment]
As seen in [a recent CI build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=990278&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=2077 ), the R package's linkage to OpenMP on macOS looks ok

```
   INFO (r-xgboost,lib/R/library/xgboost/libs/xgboost.dylib): Needed DSO lib/libomp.dylib found in conda-forge/osx-64::llvm-openmp==18.1.8=h15ab845_0
```

Going to close as resolved. If something else comes up, please raise a new issue
